HCLOUD-2925 Send execution startDate/endDate from engine
moovit-sp-gmbh/hcloud-sdk-js pull request #219
Opened 2024-09-06 21:08 UTC by grisov

Linked task: [Startdate and enddate both set to the same value in stream executions](https://app.clickup.com/t/2570196/HCLOUD-2925).

2024-09-06 21:08 UTC, ArturGrafov commented
Task linked: [HCLOUD-2925 startdate and enddate both set to the same value in stream executions](https://app.clickup.com/t/2570196/HCLOUD-2925)

2024-09-23 08:55 UTC, JorgePBrown requested changes

2024-09-23 08:55 UTC, JorgePBrown commented on src/lib/interfaces/high5/space/execution/index.ts
> +    endDate: number;
i think endDate needs to be optional.

2024-10-07 07:19 UTC, ArturGrafov approved these changes

2024-10-10 11:44 UTC, merged